
// 使用直接引入的方式进行快速开发
import './demos';
import './demos/binding';
import './demos/for';
import './demos/if';
import './demos/ui-button';
import './demos/ui-check';
import './demos/ui-dialog';
import './demos/ui-dropdown';
import './demos/ui-icon';
import './demos/ui-input';
import './demos/ui-list';
import './demos/ui-popup';
import './demos/ui-slider';
import './demos/ui-color';
import './demos/ui-stepper';
import './demos/ui-svg';
import './demos/ui-theme';
import './demos/ui-tooltip';
import './demos/ui-tree';
import './demos/ui-uploader';
import './app';
